// <auto-generated> emitted by PROBE C. Re-emit overwrites this file. </auto-generated>
namespace Acme.Customers;

public sealed record Customer
{
    public System.Guid Id { get; init; }
    public string Name { get; init; }
    public System.DateTime CreatedAt { get; init; }
}
