namespace ProbeC;

// Deterministic lowering: recipe + target config -> a set of named .cs artifacts. Same input ->
// same bytes, no model in the loop. The lowering takes the TARGET (namespace + folder) because the
// artifact's namespace and header are part of "where it lands" — the configured target shapes the
// output, which is exactly what makes an emitted file owned and placeable.
static class Lowering
{
    // One lowered file: a relative path under the target folder + its full text.
    public readonly record struct Artifact(string RelativePath, string Text);

    public static IReadOnlyList<Artifact> Lower(Recipe recipe, EmitTarget target)
    {
        var record = LowerRecord(recipe, target.Namespace);
        var summary = LowerSummary(recipe, target.Namespace);
        return [record, summary];
    }

    static Artifact LowerRecord(Recipe recipe, string ns)
    {
        var props = recipe.Fields.Select(f => $"    public {f.Type} {f.Name} {{ get; init; }}");
        var text = $$"""
            // <auto-generated> emitted by PROBE C. Re-emit overwrites this file. </auto-generated>
            namespace {{ns}};

            public sealed record {{recipe.TypeName}}
            {
            {{string.Join("\n", props)}}
            }

            """;
        return new Artifact($"{recipe.TypeName}.cs", Normalize(text));
    }

    static Artifact LowerSummary(Recipe recipe, string ns)
    {
        var names = recipe.Fields.Select(f => $"\"{f.Name}\"");
        var text = $$"""
            // <auto-generated> emitted by PROBE C. Re-emit overwrites this file. </auto-generated>
            namespace {{ns}};

            public static class {{recipe.TypeName}}Fields
            {
                public static readonly string[] All = { {{string.Join(", ", names)}} };
            }

            """;
        return new Artifact($"{recipe.TypeName}Fields.cs", Normalize(text));
    }

    static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";
}
