// <auto-generated/> AddItemToCart handler — emitted by the integration slice.
// Composes: probe A (minted models, sibling file) + probe B (wiring below) +
// probe D (return type rendered idiomatically) + position-4 glue (authored inline).
#nullable enable
using Slice.Catalog;
using Slice.Runtime;

namespace Acme.Cart;

public static class AddItemToCartHandler
{
    // Generated from the scope.Get<T>()/Ask<T>() markers in the glue below.
    public static Container RegisterDiscovered(Container container)
    {
        container.EnsureService<Repo<User>>();
        container.EnsureQuery<BookDetails>();
        return container;
    }

    public static User Handle(Scope scope, AddItemCommand command)
    {
        var users = scope.Get<Repo<User>>();
        var book = scope.Ask<BookDetails>(new BookDetailsQuery(command.BookId));
        var user = users.Load(command.Email);
        var item = new CartItem(command.BookId, command.Qty, book.Price, book.Label);
        user.AddToCart(item);
        users.Save();
        return user;
    }
}
