// <auto-generated/> AddPoints handler (Repository) — emitted by the provider probe.
// Body substituted from the `mutate` snippet; the store SURVIVES (store.Get/Save), swapped by its fill.
#nullable enable
using Probe;
using Probe.Domain;
using static Probe.Stores;

namespace Emitted;

public static class AddPointsRepositoryHandler
{
    public static User Handle(AddPointsCommand command)
    {
        var store = Repository<User>();
        var key = command.Email;
        var agg = store.Get(key);
        agg.AddPoints(command.Points);
        store.Save(key, agg);
        return agg;
    }
}
