using System.Text;
using Microsoft.CodeAnalysis;

namespace Probe;

// Deterministic lowering: the typed Mutation (its identity) + the LIFTED real-code glue
// -> an owned .cs handler. The scaffold (load/save/return + repo wiring) is RE-INTRODUCED
// here, DERIVED FROM THE TYPES — the author never wrote it. The glue lines come from
// Lift.cs (the author's real lambdas), not from a string. Same render/wire passes as the
// earlier probes (probe B wiring, probe D rendering); minting is out of scope (the
// command + models are owned, source-gen-minted types — Minted.cs).
static class Emitter
{
    public readonly record struct Artifact(string RelativePath, string Text);

    public sealed record Identity(string Aggregate, string Command)
    {
        public string FeatureName => Command.EndsWith("Command") ? Command[..^"Command".Length] : Command;
        public string Namespace => $"Acme.{Aggregate}s";
    }

    // Full handler body = TYPED SCAFFOLD (derived) + LIFTED glue (real code). The scaffold
    // emits scope.Get<Repo<TAgg>>() itself, so the same additive wiring scan that finds the
    // glue's scope.Ask<T> also registers the aggregate repo — the author wrote neither.
    public static string AssembleBody(Identity id, Lift.Glue glue)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"var __repo = scope.Get<Repo<{id.Aggregate}>>();");
        sb.AppendLine($"var agg = __repo.Load({glue.LoadKeyExpression});");
        foreach (var stmt in glue.DivergenceStatements)
            foreach (var line in stmt.Replace("\r\n", "\n").TrimEnd().Split('\n'))
                sb.AppendLine(line.TrimEnd());
        sb.AppendLine("__repo.Save();");
        sb.AppendLine("return agg;");
        return sb.ToString();
    }

    public static IReadOnlyList<Artifact> Lower(Identity id, Lift.Glue glue, string domainSource)
    {
        var model = ResolutionModel.Build(domainSource, id.Namespace);
        var body = AssembleBody(id, glue);
        var deps = WiringScan.Scan(body, "scope", model);

        var returnSymbol = model.Resolve(id.Aggregate);
        var returnType = ResolutionModel.Render(returnSymbol);

        return [HandlerFile(id, returnType, returnSymbol, body, deps)];
    }

    static Artifact HandlerFile(
        Identity id,
        string returnType,
        ITypeSymbol returnSymbol,
        string body,
        IReadOnlyList<WiringScan.Dependency> deps)
    {
        var usings = new SortedSet<string>(StringComparer.Ordinal) { "Probe.Domain" };
        foreach (var u in ResolutionModel.DeriveUsings(new[] { returnSymbol }, id.Namespace))
            usings.Add(u);

        var sb = new StringBuilder();
        sb.AppendLine($"// <auto-generated/> {id.FeatureName} handler — emitted by the extraction probe.");
        sb.AppendLine("// Body = TYPED SCAFFOLD (load/save/return + repo wiring, derived from the generics)");
        sb.AppendLine("//        + LIFTED glue (the author's real, compiler-checked lambdas — Lift.cs).");
        sb.AppendLine("#nullable enable");
        foreach (var u in usings)
            sb.AppendLine($"using {u};");
        sb.AppendLine();
        sb.AppendLine($"namespace {id.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {id.FeatureName}Handler");
        sb.AppendLine("{");

        sb.AppendLine("    // Generated from the scope.Get<T>()/Ask<T>() markers — including the scaffold's own Repo<TAggregate>.");
        sb.AppendLine("    public static Container RegisterDiscovered(Container container)");
        sb.AppendLine("    {");
        foreach (var d in deps)
        {
            var call = d.Kind == WiringScan.DepKind.Service ? "EnsureService" : "EnsureQuery";
            sb.AppendLine($"        container.{call}<{d.RenderedType}>();");
        }
        sb.AppendLine("        return container;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public static {returnType} Handle(Scope scope, {id.Command} command)");
        sb.AppendLine("    {");
        foreach (var line in body.Replace("\r\n", "\n").TrimEnd().Split('\n'))
            sb.AppendLine(line.Length == 0 ? string.Empty : "        " + line.TrimEnd());
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return new Artifact($"{id.FeatureName}.Handler.cs", Normalize(sb.ToString()));
    }

    static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";
}
