// <auto-generated/>
#nullable enable
namespace Spike;

sealed record AddNode(IExpr<int> A, IExpr<int> B) : IExpr<int>;
sealed record AssignNode(string Target, IExpr<int> Value) : IStmt;
sealed record DefineNode(IExpr<int> Value, string Var) : IStmt;
sealed record LoopNode(IExpr<int> Count, string I, Block Body) : IStmt;
sealed record ReturnNode(IExpr<int> Value) : IStmt;
