// <auto-generated/> AddItem handler — emitted by the leverage probe.
// Body = MOTIF scaffold (load/save/return + repo wiring, implied) + author divergence (slotted).
#nullable enable
using Probe.Catalog;
using Probe.Runtime;

namespace Acme.Users;

public static class AddItemHandler
{
    // Generated from the scope.Get<T>()/Ask<T>() markers — including the motif's own Repo<TAggregate>.
    public static Container RegisterDiscovered(Container container)
    {
        container.EnsureService<Repo<User>>();
        container.EnsureQuery<BookDetails>();
        return container;
    }

    public static User Handle(Scope scope, AddItemCommand command)
    {
        var __repo = scope.Get<Repo<User>>();
        var agg = __repo.Load(command.Email);
        var book = scope.Ask<BookDetails>(new BookDetailsQuery(command.BookId));
        agg.AddToCart(new CartItem(command.BookId, command.Qty, book.Price, book.Label));
        __repo.Save();
        return agg;
    }
}
