// <auto-generated/> AddPoints handler (Bucket) — emitted by the provider probe.
// Body substituted from the `mutate` snippet; the store SURVIVES (store.Get/Save), swapped by its fill.
#nullable enable
using Probe;
using Probe.Domain;
using static Probe.Stores;

namespace Emitted;

public static class AddPointsBucketHandler
{
    public static User Handle(AddPointsCommand command)
    {
        var store = Bucket<User>();
        var key = new BucketKey(command.Region);
        var agg = store.Get(key);
        agg.AddPoints(command.Points);
        store.Save(key, agg);
        return agg;
    }
}
