// <auto-generated/> PROBE B additive wiring — emitted by WiringGenerator.
#nullable enable
using System;
using System.Collections.Generic;

namespace ProbeB;

// A typed manifest of every dependency the generator statically found at the
// use-sites, plus a registration method that pre-binds them into the container.
public static partial class Wiring
{
    public sealed record Dep(string Kind, string Type);
    public sealed record HandlerManifest(string Command, IReadOnlyList<Dep> Dependencies);

    public static IReadOnlyList<HandlerManifest> Manifest { get; } = new HandlerManifest[]
    {
        new HandlerManifest("ProbeB.AddItem", new Dep[]
        {
            new Dep("Service", "ProbeB.Repo<ProbeB.User>"),
            new Dep("Query", "ProbeB.BookDetails"),
        }),
        new HandlerManifest("ProbeB.TopSalesByMonth", new Dep[]
        {
            new Dep("Service", "ProbeB.Read"),
        }),
        new HandlerManifest("ProbeB.Reindex", new Dep[]
        {
            new Dep("Service", "ProbeB.Read"),
        }),
    };

    // Pre-binds / validates every statically-discovered dependency against the
    // container. Generated additively from the markers — the lambda is untouched.
    public static void RegisterDiscovered(Container c)
    {
        // ProbeB.AddItem
        c.EnsureService<ProbeB.Repo<ProbeB.User>>();
        c.EnsureQuery<ProbeB.BookDetails>();
        // ProbeB.TopSalesByMonth
        c.EnsureService<ProbeB.Read>();
        // ProbeB.Reindex
        c.EnsureService<ProbeB.Read>();
    }
}
