// <auto-generated/> minted models — emitted by the integration slice (probe A).
#nullable enable
namespace Acme.Cart;

public sealed record CartItem(Guid BookId, int Qty, decimal Price, string Label);
public sealed record AddItemCommand(string Email, Guid BookId, int Qty);
