using System.Text.RegularExpressions;

namespace ABox.DocEngine;

public static class Outline
{
    private const string Start = "<!-- INDEX:START (generated by docengine outline — do not edit) -->";
    private const string End = "<!-- INDEX:END -->";

    public static string IndexMd(IReadOnlyList<ParsedBlock> blocks)
    {
        var lines = new List<string> { "**Outline** (generated — run `docengine outline --write`)", "" };
        var i = 0;
        while (i < blocks.Count)
        {
            var b = blocks[i];
            if (!string.IsNullOrEmpty(b.Group))
            {
                var grp = b.Group;
                var members = new List<string>();
                while (i < blocks.Count && blocks[i].Group == grp)
                {
                    var m = blocks[i];
                    var status = m.Attrs.GetValueOrDefault("status");
                    members.Add(status is not null ? $"{m.Title} ({status})" : m.Title);
                    i++;
                }
                lines.Add($"- {grp} — " + string.Join("; ", members));
            }
            else
            {
                lines.Add("- " + Titleize(b.Type));
                i++;
            }
        }
        return string.Join("\n", lines);
    }

    public static string StatusBoard(IReadOnlyList<ParsedBlock> blocks)
    {
        var phases = blocks.Where(b => b.Type == "phase").ToList();
        if (phases.Count == 0) return "";
        var output = new List<string> { "", "Phase status board:" };
        foreach (var status in new[] { "doing", "blocked", "todo", "done" })
        {
            var named = phases.Where(b => b.Attrs.GetValueOrDefault("status") == status)
                              .Select(b => b.Title).ToList();
            if (named.Count > 0) output.Add($"  {status,-8} {string.Join("  ", named)}");
        }
        return string.Join("\n", output);
    }

    public static string Inject(string src, string index)
    {
        var block = $"{Start}\n{index}\n{End}";
        if (src.Contains(Start, StringComparison.Ordinal))
            return Regex.Replace(src, Regex.Escape(Start) + ".*?" + Regex.Escape(End),
                                 block.Replace("$", "$$"), RegexOptions.Singleline);
        var at = src.IndexOf("\n## ", StringComparison.Ordinal);
        if (at < 0) throw new InvalidDataException("cannot inject index: the document has no '## ' section");
        return src[..at] + "\n\n" + block + "\n" + src[at..];
    }

    private static string Titleize(string type) =>
        string.Join(" ", type.Split('-').Select(w => w.Length == 0 ? w : char.ToUpperInvariant(w[0]) + w[1..]));
}
