// <auto-generated> emitted by PROBE C. Re-emit overwrites this file. </auto-generated>
namespace Acme.Customers;

public static class CustomerFields
{
    public static readonly string[] All = { "Id", "Name", "Email", "CreatedAt" };
}
