using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ProbeD;

// Assembles a rendered record .cs from a recipe, in one of the two styles. This is the
// deterministic lowering step — recipe + renderer in, owned C# source out. The ONLY difference
// between the two emitted variants is which SymbolDisplayFormat the renderer uses (and whether a
// derived `using` block is prepended); the recipe and this emitter are identical for both.
static class RecordEmitter
{
    public sealed record Emitted(string Source, ImmutableSortedSet<string> Usings);

    public static Emitted Idiomatic(RecordRecipe recipe, SemanticRenderer renderer, string ns)
    {
        var symbols = recipe.Fields.Select(f => renderer.Resolve(f.Type)).ToList();
        var usings = SemanticRenderer.DeriveUsings(symbols);
        var rendered = recipe.Fields
            .Zip(symbols, (f, s) => (f.Name, Type: SemanticRenderer.RenderIdiomatic(s)))
            .ToList();
        return new Emitted(Compose(recipe.Name, ns, usings, rendered), usings);
    }

    public static Emitted FullyQualified(RecordRecipe recipe, SemanticRenderer renderer, string ns)
    {
        var symbols = recipe.Fields.Select(f => renderer.Resolve(f.Type)).ToList();
        var rendered = recipe.Fields
            .Zip(symbols, (f, s) => (f.Name, Type: SemanticRenderer.RenderFullyQualified(s)))
            .ToList();
        // Fully-qualified output is self-contained: no usings derived or emitted.
        return new Emitted(Compose(recipe.Name, ns, ImmutableSortedSet<string>.Empty, rendered), ImmutableSortedSet<string>.Empty);
    }

    static string Compose(
        string name,
        string ns,
        ImmutableSortedSet<string> usings,
        IReadOnlyList<(string Name, string Type)> fields)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> — emitted by probe-d RecordEmitter.");
        sb.AppendLine("#nullable enable");
        foreach (var u in usings)
            sb.AppendLine($"using {u};");
        if (usings.Count > 0)
            sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        var parameters = string.Join(", ", fields.Select(f => $"{f.Type} {f.Name}"));
        sb.AppendLine($"public record {name}({parameters});");
        return sb.ToString();
    }
}
