using System.Text;
using Microsoft.CodeAnalysis;

namespace Probe;

// Deterministic lowering: a MutationRecipe -> owned .cs artifacts. The motif's
// scaffold is RE-INTRODUCED here (load/save/return/repo-wiring); the author never
// wrote it. Same machinery as the integration slice (mint -> resolve -> wire ->
// render -> assemble), but the handler body the wiring/glue passes see is the
// MOTIF-EXPANDED body, not an author-written string copy of the whole handler.
static class Emitter
{
    public readonly record struct Artifact(string RelativePath, string Text);

    // The full handler body = MOTIF SCAFFOLD (implied) + author DIVERGENCE (slotted).
    // This is what makes the wiring scan find Repo<TAggregate> WITHOUT the author
    // writing scope.Get<Repo<User>>(): the motif emits that marker itself, so the
    // same additive scan (probe B) registers the aggregate repo automatically.
    public static string ExpandHandlerBody(MutationRecipe r)
    {
        var sb = new StringBuilder();
        // --- motif scaffold (implied): load the aggregate by key ---
        sb.AppendLine($"var __repo = scope.Get<{r.Repo}>();");
        sb.AppendLine($"var {r.AggregateVar} = __repo.Load({r.LoadKey});");
        // --- author divergence (slotted): the irreducible business logic ---
        foreach (var line in r.Divergence.Replace("\r\n", "\n").TrimEnd().Split('\n'))
            sb.AppendLine(line.TrimEnd());
        // --- motif scaffold (implied): persist + return the mutated aggregate ---
        sb.AppendLine("__repo.Save();");
        sb.AppendLine($"return {r.AggregateVar};");
        return sb.ToString();
    }

    public static string MintModelsSource(MutationRecipe recipe, ResolutionModel? model = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> minted models — emitted by the leverage probe (probe A).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {recipe.Namespace};");
        sb.AppendLine();
        foreach (var m in recipe.AllModels)
        {
            var fields = m.Fields.Select(f =>
            {
                var rendered = model is null ? f.Type : ResolutionModel.Render(model.Resolve(f.Type));
                return $"{rendered} {f.Name}";
            });
            sb.AppendLine($"public sealed record {m.Name}({string.Join(", ", fields)});");
        }
        return sb.ToString();
    }

    public static IReadOnlyList<Artifact> Lower(MutationRecipe recipe, string catalogSource)
    {
        // 1) MINT (probe A): lower minted models, bootstrap-rendered.
        var bootstrap = ResolutionModel.Build(catalogSource, MintModelsSource(recipe), recipe.Namespace);
        var modelsSource = MintModelsSource(recipe, bootstrap);

        // 2) Build the shared resolution model over catalog + minted models.
        var model = ResolutionModel.Build(catalogSource, modelsSource, recipe.Namespace);

        // 3) Expand the motif: scaffold + divergence -> the full handler body.
        var handlerBody = ExpandHandlerBody(recipe);

        // 4) WIRE (probe B): scan the EXPANDED body — the motif's scope.Get<Repo<TAgg>>
        //    AND the divergence's scope.Ask<T> both surface, uniformly.
        var deps = WiringScan.Scan(handlerBody, "scope", model);

        // 5) RENDER (probe D): the return type is the aggregate (motif-implied).
        var returnSymbol = model.Resolve(recipe.Aggregate);
        var returnType = ResolutionModel.Render(returnSymbol);

        var modelFile = ModelFile(recipe, modelsSource);
        var handlerFile = HandlerFile(recipe, returnType, returnSymbol, handlerBody, deps);
        return [modelFile, handlerFile];
    }

    static Artifact ModelFile(MutationRecipe recipe, string modelsSource) =>
        new($"{recipe.FeatureName}.Models.cs", Normalize(modelsSource));

    static Artifact HandlerFile(
        MutationRecipe recipe,
        string returnType,
        ITypeSymbol returnSymbol,
        string handlerBody,
        IReadOnlyList<WiringScan.Dependency> deps)
    {
        var usings = new SortedSet<string>(StringComparer.Ordinal)
        {
            "Probe.Catalog",
            "Probe.Runtime",
        };
        foreach (var u in ResolutionModel.DeriveUsings(new[] { returnSymbol }, recipe.Namespace))
            usings.Add(u);

        var sb = new StringBuilder();
        sb.AppendLine($"// <auto-generated/> {recipe.FeatureName} handler — emitted by the leverage probe.");
        sb.AppendLine("// Body = MOTIF scaffold (load/save/return + repo wiring, implied) + author divergence (slotted).");
        sb.AppendLine("#nullable enable");
        foreach (var u in usings)
            sb.AppendLine($"using {u};");
        sb.AppendLine();
        sb.AppendLine($"namespace {recipe.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {recipe.FeatureName}Handler");
        sb.AppendLine("{");

        sb.AppendLine("    // Generated from the scope.Get<T>()/Ask<T>() markers — including the motif's own Repo<TAggregate>.");
        sb.AppendLine("    public static Container RegisterDiscovered(Container container)");
        sb.AppendLine("    {");
        foreach (var d in deps)
        {
            var call = d.Kind == WiringScan.DepKind.Service ? "EnsureService" : "EnsureQuery";
            sb.AppendLine($"        container.{call}<{d.RenderedType}>();");
        }
        sb.AppendLine("        return container;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public static {returnType} Handle(Scope scope, {recipe.Command.Name} command)");
        sb.AppendLine("    {");
        foreach (var line in handlerBody.Replace("\r\n", "\n").TrimEnd().Split('\n'))
            sb.AppendLine(line.Length == 0 ? string.Empty : "        " + line.TrimEnd());
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return new Artifact($"{recipe.FeatureName}.Handler.cs", Normalize(sb.ToString()));
    }

    static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";
}
