// <auto-generated/> minted models — emitted by the leverage probe (probe A).
#nullable enable
namespace Acme.Users;

public sealed record AddItemCommand(string Email, Guid BookId, int Qty);
public sealed record CartItem(Guid BookId, int Qty, decimal Price, string Label);
