using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Probe;

// Lower a recipe to an owned handler by SUBSTITUTING the `mutate` snippet — the same
// mechanism as the original spike's Loop -> for. Each snippet PARAM becomes a `var <param> =
// <fill>;` local (store <- the store: arg, key <- the key: arg); Block.Of("body") becomes the
// lifted body. store.Get / store.Save survive verbatim. No provider table, no verb rewrite:
// swapping the store is entirely a different `store:` fill.
static class Emitter
{
    public readonly record struct Artifact(string RelativePath, string Text);

    static readonly Regex BlockCall = new(@"Block\s*\.\s*Of\s*\(\s*""(\w+)""\s*\)\s*;");

    public static Artifact Lower(Lift.Recipe recipe)
    {
        var snippet = LoadSnippet("mutate");
        var body = RenderSnippet(snippet, recipe);
        var tag = recipe.StoreName;

        var cls = $"{recipe.FeatureName}{tag}Handler";
        var full = $$"""
            // <auto-generated/> {{recipe.FeatureName}} handler ({{tag}}) — emitted by the provider probe.
            // Body substituted from the `mutate` snippet; the store SURVIVES (store.Get/Save), swapped by its fill.
            #nullable enable
            using Probe;
            using Probe.Domain;
            using static Probe.Stores;

            namespace Emitted;

            public static class {{cls}}
            {
                public static {{recipe.Aggregate}} Handle({{recipe.Command}} command)
                {
            {{Indent(body, 8)}}
                }
            }
            """;

        return new Artifact($"{recipe.FeatureName}.{tag}.Handler.cs", Normalize(full));
    }

    // params -> locals from the expression fills; body statements with Block.Of filled.
    static string RenderSnippet(MethodDeclarationSyntax snippet, Lift.Recipe recipe)
    {
        var locals = snippet.ParameterList.Parameters.Select(p =>
        {
            var name = p.Identifier.ValueText;
            return recipe.ExprFills.TryGetValue(name, out var fill)
                ? $"var {name} = {fill};"
                : throw new InvalidOperationException($"the recipe has no '{name}:' argument for the snippet param.");
        });

        var statements = snippet.Body!.Statements.Select(st => st.NormalizeWhitespace().ToFullString());
        var body = BlockCall.Replace(string.Join("\n", statements), m => FillBlock(m.Groups[1].Value, recipe));

        return string.Join("\n", locals) + "\n" + body;
    }

    static string FillBlock(string id, Lift.Recipe recipe) =>
        recipe.BlockFills.TryGetValue(id, out var fill)
            ? fill
            : throw new InvalidOperationException($"the mutate snippet has an unfilled Block.Of(\"{id}\").");

    static MethodDeclarationSyntax LoadSnippet(string name)
    {
        var root = CSharpSyntaxTree.ParseText(File.ReadAllText(Snippets.SourcePath)).GetRoot();
        foreach (var method in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
        {
            var attr = method.AttributeLists.SelectMany(a => a.Attributes)
                .FirstOrDefault(a => a.Name.ToString() is "Snippet" or "SnippetAttribute");
            if (attr?.ArgumentList?.Arguments.FirstOrDefault()?.Expression is LiteralExpressionSyntax lit
                && lit.Token.ValueText == name)
                return method;
        }
        throw new InvalidOperationException($"no [Snippet(\"{name}\")] in {Snippets.SourcePath}.");
    }

    static string Indent(string text, int spaces)
    {
        var pad = new string(' ', spaces);
        return string.Join("\n", text.Replace("\r\n", "\n").Split('\n')
            .Select(l => l.Length == 0 ? l : pad + l));
    }

    static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";
}
