<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\ABox.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Domain\Agents\ABox.Domain.Agents.csproj" />
    <ProjectReference Include="Api\ABox.Threads.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ABox.Threads.Tests" />
  </ItemGroup>

</Project>
