<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\..\tests\TestProject.props" />

  <PropertyGroup>
    <RootNamespace>ABox.Threads.Tests</RootNamespace>
    <AssemblyName>ABox.Threads.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="TestsSourceDir" Value="$(MSBuildProjectDirectory)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\tests\Harness\ABox.Tests.Harness.csproj" />
    <ProjectReference Include="..\ABox.Threads.csproj" />
    <ProjectReference Include="..\..\..\Infrastructure\ABox.Infrastructure.csproj" />
  </ItemGroup>

</Project>
