using System.Text;
using Microsoft.CodeAnalysis;

namespace Slice;

// Deterministic lowering: FeatureRecipe -> a set of owned .cs artifacts. This is
// where all five mechanics MEET in one pass set. Same recipe + same catalog ->
// same bytes, no model in the loop. Each artifact is one file under the target.
static class Emitter
{
    public readonly record struct Artifact(string RelativePath, string Text);

    // The minted models as record source, lowered FIRST and standalone so the
    // ResolutionModel can be built over them (probe A as data + probe E: the
    // forward-ref source the rest of the feature resolves against). Rendered field
    // types use the model so a model field can itself name a BCL/generic type.
    public static string MintModelsSource(FeatureRecipe recipe, ResolutionModel? model = null)
    {
        // First call (model is null) renders field types fully-qualified-free via a
        // *bootstrap* model built from catalog only — but minted models reference
        // only BCL types in their fields here, so a catalog-only model resolves them.
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> minted models — emitted by the integration slice (probe A).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {recipe.Namespace};");
        sb.AppendLine();
        foreach (var m in recipe.Models)
        {
            var fields = m.Fields.Select(f =>
            {
                var rendered = model is null ? f.Type.Text : ResolutionModel.Render(model.Resolve(f.Type));
                return $"{rendered} {f.Name}";
            });
            sb.AppendLine($"public sealed record {m.Name}({string.Join(", ", fields)});");
        }
        return sb.ToString();
    }

    // The full feature emission: model file + handler file (glue + wiring).
    public static IReadOnlyList<Artifact> Lower(FeatureRecipe recipe, string catalogSource)
    {
        // 1) MINT (probe A): lower minted models to source, bootstrap-rendered.
        var bootstrap = ResolutionModel.Build(catalogSource, MintModelsSource(recipe), recipe.Namespace);
        var modelsSource = MintModelsSource(recipe, bootstrap);

        // 2) Build the shared resolution model over catalog + minted models, so
        //    render (D), wire (B) and the glue return type all resolve the minted
        //    types as real symbols in the feature namespace (probe E).
        var model = ResolutionModel.Build(catalogSource, modelsSource, recipe.Namespace);

        // 3) WIRE (probe B): scan the glue text for scope.Get/Ask markers.
        var deps = WiringScan.Scan(recipe.Glue.Body, "scope", model);

        // 4) RENDER (probe D): the handler's return type, idiomatic + derived usings.
        var returnSymbol = model.Resolve(recipe.Glue.Returns);
        var returnType = ResolutionModel.Render(returnSymbol);

        var modelFile = ModelFile(recipe, modelsSource);
        var handlerFile = HandlerFile(recipe, returnType, returnSymbol, deps);
        return [modelFile, handlerFile];
    }

    static Artifact ModelFile(FeatureRecipe recipe, string modelsSource) =>
        new($"{recipe.FeatureName}.Models.cs", Normalize(modelsSource));

    static Artifact HandlerFile(
        FeatureRecipe recipe,
        string returnType,
        ITypeSymbol returnSymbol,
        IReadOnlyList<WiringScan.Dependency> deps)
    {
        // Derive usings for the handler: the return type's namespaces + the catalog
        // + runtime namespaces the glue and wiring reference. The minted models are
        // in the feature's own namespace, so no using is needed for them (probe E,
        // same-namespace) — DeriveUsings drops the feature namespace.
        var usings = new SortedSet<string>(StringComparer.Ordinal)
        {
            "Slice.Catalog",
            "Slice.Runtime",
        };
        foreach (var u in ResolutionModel.DeriveUsings(new[] { returnSymbol }, recipe.Namespace))
            usings.Add(u);

        var sb = new StringBuilder();
        sb.AppendLine($"// <auto-generated/> {recipe.FeatureName} handler — emitted by the integration slice.");
        sb.AppendLine("// Composes: probe A (minted models, sibling file) + probe B (wiring below) +");
        sb.AppendLine("// probe D (return type rendered idiomatically) + position-4 glue (authored inline).");
        sb.AppendLine("#nullable enable");
        foreach (var u in usings)
            sb.AppendLine($"using {u};");
        sb.AppendLine();
        sb.AppendLine($"namespace {recipe.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {recipe.FeatureName}Handler");
        sb.AppendLine("{");

        // The wiring registration (probe B), additive — pre-binds every discovered dep.
        sb.AppendLine("    // Generated from the scope.Get<T>()/Ask<T>() markers in the glue below.");
        sb.AppendLine("    public static Container RegisterDiscovered(Container container)");
        sb.AppendLine("    {");
        foreach (var d in deps)
        {
            var call = d.Kind == WiringScan.DepKind.Service ? "EnsureService" : "EnsureQuery";
            sb.AppendLine($"        container.{call}<{d.RenderedType}>();");
        }
        sb.AppendLine("        return container;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // The handler: the glue body (position 4) dropped verbatim into the typed
        // slot. `scope` and `command` are the slot's bound names; the body is the
        // author's irreducible business logic, untouched.
        sb.AppendLine($"    public static {returnType} Handle(Scope scope, {recipe.Command} command)");
        sb.AppendLine("    {");
        foreach (var line in recipe.Glue.Body.Split('\n'))
            sb.AppendLine(line.Length == 0 ? string.Empty : "        " + line.TrimEnd());
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return new Artifact($"{recipe.FeatureName}.Handler.cs", Normalize(sb.ToString()));
    }

    static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";
}
